# Generated by Django 5.1 on 2024-11-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_category_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.CharField(max_length=800),
        ),
    ]
