# Generated by Django 5.1 on 2024-11-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
